Public Class Form1
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Form2.Show()
        Form2.TextBox1.Text = TextBox1.Text
        Form2.TextBox2.Text = TextBox2.Text
        Form2.TextBox3.Text = TextBox33.Text
        Form2.TextBox8.Text = TextBox34.Text
        Form2.TextBox5.Text = TextBox35.Text
        Form2.TextBox10.Text = TextBox36.Text
        Form2.TextBox6.Text = TextBox37.Text
        Form2.TextBox38.Text = TextBox38.Text
        Form2.TextBox39.Text = TextBox39.Text
        Form2.TextBox40.Text = TextBox40.Text
        Form2.TextBox41.Text = TextBox41.Text
        Form2.TextBox42.Text = TextBox42.Text
        Form2.TextBox44.Text = TextBox44.Text
        Form2.TextBox13.Text = ComboBox1.Text
        Form2.TextBox19.Text = ComboBox2.Text
        Form2.TextBox18.Text = ComboBox3.Text
        Form2.TextBox9.Text = ComboBox4.Text
        Form2.TextBox14.Text = ComboBox5.Text
        Form2.TextBox4.Text = ComboBox6.Text
        Form2.TextBox15.Text = ComboBox7.Text
        Form2.TextBox20.Text = ComboBox8.Text
        Form2.TextBox21.Text = ComboBox9.Text
        Form2.TextBox16.Text = ComboBox10.Text
        Form2.TextBox22.Text = ComboBox11.Text
        Form2.TextBox17.Text = ComboBox12.Text
        Form2.TextBox11.Text = ComboBox13.Text
        Form2.TextBox12.Text = ComboBox14.Text
        Form2.TextBox7.Text = ComboBox15.Text
        Form2.TextBox23.Text = ComboBox16.Text
        Form2.TextBox33.Text = ComboBox17.Text
        Form2.TextBox28.Text = ComboBox18.Text
        Form2.TextBox24.Text = ComboBox19.Text
        Form2.TextBox29.Text = ComboBox20.Text
        Form2.TextBox34.Text = ComboBox21.Text
        Form2.TextBox25.Text = ComboBox22.Text
        Form2.TextBox30.Text = ComboBox23.Text
        Form2.TextBox35.Text = ComboBox24.Text
        Form2.TextBox26.Text = ComboBox25.Text
        Form2.TextBox31.Text = ComboBox26.Text
        Form2.TextBox36.Text = ComboBox27.Text
        Form2.TextBox27.Text = ComboBox28.Text
        Form2.TextBox32.Text = ComboBox29.Text
        Form2.TextBox37.Text = ComboBox30.Text
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Form2.Show()
        Form2.TextBox1.Text = ""
        Form2.TextBox2.Text = ""
        Form2.TextBox3.Text = ""
        Form2.TextBox8.Text = ""
        Form2.TextBox5.Text = ""
        Form2.TextBox10.Text = ""
        Form2.TextBox6.Text = ""
        Form2.TextBox38.Text = ""
        Form2.TextBox39.Text = ""
        Form2.TextBox40.Text = ""
        Form2.TextBox41.Text = ""
        Form2.TextBox42.Text = ""
        Form2.TextBox44.Text = ""
        Form2.TextBox13.Text = ""
        Form2.TextBox19.Text = ""
        Form2.TextBox18.Text = ""
        Form2.TextBox9.Text = ""
        Form2.TextBox14.Text = ""
        Form2.TextBox4.Text = ""
        Form2.TextBox15.Text = ""
        Form2.TextBox20.Text = ""
        Form2.TextBox21.Text = ""
        Form2.TextBox16.Text = ""
        Form2.TextBox22.Text = ""
        Form2.TextBox17.Text = ""
        Form2.TextBox11.Text = ""
        Form2.TextBox12.Text = ""
        Form2.TextBox7.Text = ""
        Form2.TextBox23.Text = ""
        Form2.TextBox33.Text = ""
        Form2.TextBox28.Text = ""
        Form2.TextBox24.Text = ""
        Form2.TextBox29.Text = ""
        Form2.TextBox34.Text = ""
        Form2.TextBox25.Text = ""
        Form2.TextBox30.Text = ""
        Form2.TextBox35.Text = ""
        Form2.TextBox26.Text = ""
        Form2.TextBox31.Text = ""
        Form2.TextBox36.Text = ""
        Form2.TextBox27.Text = ""
        Form2.TextBox32.Text = ""
        Form2.TextBox37.Text = ""
    End Sub
End Class
